version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*" # Applies to all dependencies
        update-types: ["version-update:semver-major"] # Ignores major version updates
