AWSTemplateFormatVersion: 2010-09-09
Description: >-
  web-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Version:
    Type: String
    Description: The version of the application

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${putItemFunction}"
      RetentionInDays: 30

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Policies:
        - AmazonSSMReadOnlyAccess
      Handler: src/put-item.handler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - arm64
      Events:
        RootResource:
          PayloadFormatVersion: "2.0"
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          VERSION: !Ref Version
          POWERTOOLS_LOGGER_LOG_EVENT: true
          POWERTOOLS_LOG_LEVEL: DEBUG
          POWERTOOLS_TRACE_ENABLED: true
          POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
          POWERTOOLS_TRACER_CAPTURE_ERROR: true
          POWERTOOLS_SERVICE_NAME: hello-ts
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2020"
        Sourcemap: true
        EntryPoints:
          - src/put-item.ts

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  LogGroupName:
    Value: !Ref LogGroup
