AWSTemplateFormatVersion: 2010-09-09
Description: >-
  web-app
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${putItemFunction}"
      RetentionInDays: 30

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonSSMReadOnlyAccess
      Handler: src/put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Events:
        RootResource:
          PayloadFormatVersion: "2.0"
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2020"
        Sourcemap: true
        EntryPoints:
          - src/put-item.ts

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  LogGroupName:
    Value: !Ref LogGroup

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
