name: "Install"
description: "Sets up Node, and installs dependencies"

inputs:
  fetch-depth:
    default: "1"
    required: false
  persist-credentials:
    default: true
    required: false

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    - run: npm ci
    - run: npm test
