name: Quality

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: npm run lint

  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Prettier check
        run: npm run prettier-check
