on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/composite-actions/install
      - run: npm test
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - run: make deploy
      - id: get_api_url
        run: |
          echo ENDPOINT=$(aws cloudformation describe-stacks --stack-name powertools-demo --query 'Stacks[0].Outputs[?OutputKey==`WebEndpoint`].OutputValue' --output text) >> "$GITHUB_OUTPUT"
          echo LOGGROUP=$(aws cloudformation describe-stacks --stack-name powertools-demo --query 'Stacks[0].Outputs[?OutputKey==`LogGroupName`].OutputValue' --output text) >> "$GITHUB_OUTPUT"
      - env:
          URL: ${{ steps.get_api_url.outputs.ENDPOINT }}
        run: |
          echo "# We deployed! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Version $(make showversion)" >> $GITHUB_STEP_SUMMARY
          echo "- Endpoint $URL" >> $GITHUB_STEP_SUMMARY
      - name: Test API Gateway URL
        env:
          URL: ${{ steps.get_api_url.outputs.ENDPOINT }}
        run: curl -s -X POST $URL
      - env:
          LOGGROUP: ${{ steps.get_api_url.outputs.LOGGROUP }}
        run: aws logs tail $LOGGROUP
