name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - run: make deploy
      - run: make apigw
      # get the api gateway url
      - name: Get API Gateway URL
        id: get_api_url
        run: echo ENDPOINT=$(aws cloudformation describe-stacks --stack-name powertools-demo --query 'Stacks[0].Outputs[?OutputKey==`WebEndpoint`].OutputValue' --output text) >> "$GITHUB_OUTPUT"
      - name: Generate list using Markdown
        env:
          URL: ${{ steps.get_api_url.ENDPOINT }}
        run: |
          echo "# We deployed! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Version $(make showversion)" >> $GITHUB_STEP_SUMMARY
          echo "- Endpoint $URL" >> $GITHUB_STEP_SUMMARY
      -  name: Test API Gateway URL
         env:
            URL: ${{ steps.get_api_url.ENDPOINT }}
         run: curl -s -v -X POST ${{ env.URL }}