name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Install dependencies
        run: npm install
      - name: Build
        run: make build
      - name: test
        run: make test
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - name: Deploy
        run: make deploy
      - name: API gw info
        run: make apigw
